### PR TITLE
TransformWithCovariance: performance improvements

### PR DESCRIPTION
**Pull request by arneboe**
Several performance improvements to TransformWithCovariance that overall improve the performance
of the TransformGraph significantly.

### CODE REVIEW

**Comment by arneboe** [comment]
Can someone please merge this? 
Together with some changes in the TransformGraph it solves all performance problems of the Graph :)

@jhidalgocarrio @goldhoorn

**Comment by arneboe** [comment]
@2maz

**Comment by arneboe** [comment]
Please merge this. The changes might seem minor but they significantly improve the performance of the envire::core::TransformGraph which makes heavy use of the TransformWithCovariance.

**Comment by jakobs** [comment]
looks good to me.

**Pull request merged**
