### PR TITLE
Fixed color ordering of pointcloudes

### PR DESCRIPTION
**Pull request by goldhoorn**
This patch fixed VizkitPointCloudeVisualization

### CODE REVIEW

**Comment by goldhoorn** [comment]
pong ?

**Comment by goldhoorn** [comment]
bit importand this fixed a memory out-of-array-acces (len + 1 access)

**Comment by doudou** [comment]
I really can't comment on this. Can anybody that has experience with these viz3d plugins have a look ? @jakobs ? @D-Alex ?

**Comment by goldhoorn** [comment]
It's really only a minor fix.

The problem was that i was increased before the first access.
therefore pointCloud.colors[i][0] index 0 was never used. The last-used one was size()+1.
Really stupid misstake

The index of colors should equal the index of the iterator access but i don't want to change to a integer based iterator for the points-list (which would be clearer then).

**Comment by jakobs** [comment]
I merge it, but why not do a proper fix like you suggest?

**Pull request merged**
