### PR TITLE
DepthMap: fixed an issue when computing the step resolution in the polar case

### PR DESCRIPTION
**Pull request by saarnold**
Thanks @Rauldg for reporting this issue.

It also add missing unit test for this case.

### CODE REVIEW

**Comment by chhtz** [comment]
This does also fix the issue which was fixed in PR #87.
I don't know, if we want to allow `DepthMap`s which turn more than a full revolution (which could be helpful, when the robot mounting the LIDAR is turning while the LIDAR records, but one wants to be sure to actually have a full cycle).

**Comment by Rauldg** [comment]
IMO, the sample should finish as soon as the sensor has covered the given range, according to its internal initial state, additional image processing should be performed latter. Otherwise, to take samples the sensor task would need the position of the robot and that makes it more complicated for simple use cases.

**Comment by saarnold** [comment]
By using two angles to define a range having a constant angular resolution, this is not possible. We would need to add more meta information, which would overload this type even more and I'm against that. (One still could encode it by just using the non-discrete form)

In your use-case you would need to know how you have moved in the component producing the DepthMap, in this case you could simply transform the measurements before sending the full cycle.

**Comment by chhtz** [comment]
It would not be possible by providing two `base::Angle`s, but by giving two absolute angles (which include the number of revolutions), e.g., give start angle 0 and end angle 10pi, to encode 5 full revolutions. Alternatively, one could provide the starting angle and the angle step, instead of the start and end angle. 
But admittedly, that can just as easy be encoded by 5 successive DepthMaps. So I'm ok with the PR as it is.

**Comment by jakobs** [comment]
There is the AngleSegment class in the Ange.hpp file. Does this have any impact on your discussion?

**Comment by chhtz** [comment]
I guess `AngleSegment` would make sense if `DepthMap` was always used with start and end-angle. Currently, there is an option to either specify every angle or to specify start and end-angle.

**Comment by jmachowinski** [comment]
Angle segment for start/end is undefined. Or you would need to assume a direction.

**Comment by jmachowinski** [comment]
I just remembered, the main problem was that you could not define a full turn with it.

**Comment by Rauldg** [comment]
Any reason not to merge?

**Comment by jmachowinski** [comment]
looks good to me

**Comment by chhtz** [comment]
Overall I'd still prefer storing non-normalized angles here. This would allow to safely define an interval [0, 2π] (or [-π, +π]) without having to worry that it ends up to be [0, ε] (where ε is from a rounding error when normalizing 2π). 
Essentially, in `computeResolution` just replace the `base::Angle` by `double` and optionally make an assertion that `.front()` is smaller than `.back()` (or the other way around).

**Comment by saarnold** [comment]
> This would allow to safely define an interval [0, 2π] (or [-π, +π]) without having to worry that it ends up to be [0, ε] (where ε is from a rounding error when normalizing 2π). 

Yes this could be an issue.

> Essentially, in computeResolution just replace the base::Angle by double and optionally make an assertion that .front() is smaller than .back() (or the other way around).

Currently both [0.5π, -0.5π] and [-0.5π, 0.5π] are valid ranges, one to the front and one to the back. With the constraint that the data is ordered row major from the left to the right.
Changing this is possible, but would mean that the range to the back needs to be defined [-0.5π, -1.5π].
Then [-0.5π, 0.5π] for the horizontal case would mean that the data is ordered from the right to the left instead.
In the hope that no one was using it that way we can change this.

**Comment by chhtz** [comment]
I agree, my only concern with my suggestion would be that we break existing code as well.

From the point of usability I think  `[-0.5π, -1.5π]` (if it goes clockwise?) is much more intuitive than knowing that `[-0.5π, 0.5π]` actually goes `-0.5π --> -π == +π --> 0.5π`. Furthermore, with proper assertions I think almost all wrong parameters should get caught.

**Comment by saarnold** [comment]
Ok essentially we are back to the origin PR now :)
I updated the documentation and unit tests.

> Furthermore, with proper assertions I think almost all wrong parameters should get caught.

We could throw an invalid argument exception when angles are ordered differently to the expected direction. But since it wouldn't break the general function of the type I would still leave that to the user and don't be too restrictive here.
According to the documentation there should be only one correct way of course.

**Comment by saarnold** [comment]
Ping! From my side this can be merged.

**Pull request merged**
