### PR TITLE
Update logging

### PR DESCRIPTION
**Pull request by jakobs**

### CODE REVIEW

**Comment by doudou** [comment]
ping @jakobs

**Comment by 2maz** [comment]
I just merged the uncritial bits / fixes (commit: 028d446 and  40b84f2).
The remaining point of discussions: how the logger should behave in Release mode and others and how to control the behaviour?

**Comment by doudou** [comment]
> I just merged the uncritial bits / fixes (commit: 028d446 and 40b84f2).

@jakobs: could you rebase ?

**Comment by jakobs** [comment]
Just rebased. Still need to decide where the decision to build in the logging comes from. In my opinion this should be decided in the cmake, which will then set the log level explicitly.

**Comment by goldhoorn** [comment]
Do we need to make a public decision here?
Setting on all projects a debug level is in autoproj quite easy:

pkg.define("BASE_LOG_PRIORITY",5) for example....

**Comment by doudou** [comment]
@goldhoorn: :+1:

**Comment by goldhoorn** [comment]
In rock we have no default way of building a release (yet) if someone intorduce this (e.g. setting stable to all packages) then he could add this too. For the time beeing i merge this...

**Pull request merged**
