### PR TITLE
viz: simplify sonar beam visualization code

### PR DESCRIPTION
**Pull request by doudou**
Instead of doing its own management of the sonar stream, it now uses the
keepOldData features to achieve the same result as the existing code, but
a lot simpler (and easy to change at runtime). The beams are now
accurately represented (i.e. are plus/minus a half-width around the
center bearing). Finally, bearing=0 means beam along X.

### CODE REVIEW

**Comment by D-Alex** [comment]
:+1: 

I just went through the code and added some comments while reading. But even without the changes the code is a good improvements compared to the original one.

**Comment by doudou** [comment]
Hey. Next time, make sure that you comment in the "FIles changes" section of the PR, this makes looking at them really a lot easier, and makes sure that we don't lose any comment if the submitter rebases or amends commits.

**Comment by D-Alex** [comment]
sorry, I did not know there is a different.

**Comment by doudou** [comment]
Other than that, I've updated the code according to your comments. Can you have a look and merge if you're fine with the result ?

**Comment by D-Alex** [comment]
I cannot see any changes? - have you pushed to a different branch?

**Comment by goldhoorn** [comment]
@doudou did you forgot this?

**Comment by doudou** [comment]
Nope... but did not have time to fix / update / ...

**Pull request closed without merging**
